### ISSUE TITLE
[cetic/nifi] Add support for istio

### ISSUE THREAD

**Issue by dsarosi** [cetic/helm-nifi#111]
**Is your feature request related to a problem? Please describe.**
When using istio the node has trouble connecting with the cluster.   

`2020-12-08 03:19:03,514 ERROR [Curator-Framework-0] o.a.c.f.imps.CuratorFrameworkImpl Background retry gave up
org.apache.curator.CuratorConnectionLossException: KeeperErrorCode = ConnectionLoss
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:972)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.backgroundOperationsLoop(CuratorFrameworkImpl.java:943)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.access$300(CuratorFrameworkImpl.java:66)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl$4.call(CuratorFrameworkImpl.java:346)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Describe the solution you'd like**
It would be nice if the helm chart could support istio.

**Describe alternatives you've considered**
Disabling the istio sidecar which works fine, but one would lose some trafficking features.

**Additional context**

**Comment by alexnuttinck** [comment]
Hello @dsarosi,

Thanks for your Feature request. It is not at the agenda, but we are open to PR.

**Comment by bmgante** [comment]
Hi,
As workaround, is it only required to disable isto in sts annotations or is it also required to disable isto for registry and zookeeper charts?

`sts:
  # Parallel podManagementPolicy for faster bootstrap and teardown. Default is OrderedReady.
  podManagementPolicy: Parallel
  AntiAffinity: soft
  useHostNetwork: null
  hostPort: null
  pod:
    annotations:
      security.alpha.kubernetes.io/sysctls: net.ipv4.ip_local_port_range=10000 65000
      **sidecar.istio.io/inject: "false"**
      #prometheus.io/scrape: "true"  
`

**Comment by bmgante** [comment]
Is there some improvement to support istio?
