### ISSUE TITLE
[cetic/nifi] issue title

### ISSUE THREAD

**Issue by pietrogerace1994** [cetic/helm-nifi#195]
Hello I am facing some problems running this project on Openshift 4.7.
Here there is the log I get in the console

`updating nifi.remote.input.host in /opt/nifi/nifi-current/conf/nifi.properties`
`updating nifi.cluster.node.address in /opt/nifi/nifi-current/conf/nifi.properties`
`updating nifi.zookeeper.connect.string in /opt/nifi/nifi-current/conf/nifi.properties`
`updating nifi.web.http.host in /opt/nifi/nifi-current/conf/nifi.properties`
`updating nifi.web.proxy.host in /opt/nifi/nifi-current/conf/nifi.properties`
`updating nifi.web.http.network.interface.default in /opt/nifi/nifi-current/conf/nifi.properties`
`updating nifi.web.http.network.interface.lo in /opt/nifi/nifi-current/conf/nifi.properties`
`NiFi running with PID 26.`
`Java home: /usr/local/openjdk-8`
`NiFi home: /opt/nifi/nifi-current`
`Bootstrap Config File: /opt/nifi/nifi-current/conf/bootstrap.conf`
`2021-11-20 16:43:42,580 INFO [main] org.apache.nifi.bootstrap.Command Starting Apache NiFi...
`2021-11-20 16:43:42,580 INFO [main] org.apache.nifi.bootstrap.Command Working Directory: /opt/nifi/nifi-current
`2021-11-20 16:43:42,581 INFO [main] org.apache.nifi.bootstrap.Command Command: /usr/local/openjdk-8/bin/java -classpath `/opt/nifi/nifi-current/./conf:/opt/nifi/nifi-current/./lib/jul-to-slf4j-1.7.30.jar:/opt/nifi/nifi-current/./lib/slf4j-api-1.7.30.jar:/opt/nifi/nifi-`current/./lib/nifi-stateless-api-1.14.0.jar:/opt/nifi/nifi-current/./lib/jcl-over-slf4j-1.7.30.jar:/opt/nifi/nifi-current/./lib/nifi-server-api-1.14.0.jar:/opt/nifi/nifi-current/./lib/jetty-schemas-3.1.jar:/opt/nifi/nifi-current/./lib/log4j-over-slf4j-1.7.30.jar:/opt/nifi/nifi-current/./lib/logback-core-1.2.3.jar:/opt/nifi/nifi-current/./lib/logback-classic-1.2.3.jar:/opt/nifi/nifi-current/./lib/nifi-runtime-1.14.0.jar:/opt/nifi/nifi-current/./lib/nifi-framework-api-1.14.0.jar:/opt/nifi/nifi-current/./lib/nifi-nar-utils-1.14.0.jar:/opt/nifi/nifi-current/./lib/nifi-property-utils-1.14.0.jar:/opt/nifi/nifi-current/./lib/javax.servlet-api-3.1.0.jar:/opt/nifi/nifi-current/./lib/nifi-api-1.14.0.jar:/opt/nifi/nifi-current/./lib/nifi-properties-1.14.0.jar:/opt/nifi/nifi-current/./lib/nifi-stateless-bootstrap-1.14.0.jar `-Dorg.apache.jasper.compiler.disablejsr199=true -Xmx2g -Xms2g -Djava.security.egd=file:/dev/urandom `-Dsun.net.http.allowRestrictedHeaders=true -Djava.net.preferIPv4Stack=true -Djava.awt.headless=true `-Djava.protocol.handler.pkgs=sun.net.www.protocol -Dnifi.properties.file.path=/opt/nifi/nifi-current/./conf/nifi.properties `-Dnifi.bootstrap.listen.port=44929 -Dapp=NiFi -Dorg.apache.nifi.bootstrap.config.log.dir=/opt/nifi/nifi-current/logs `org.apache.nifi.NiFi`
`2021-11-20 16:43:42,623 INFO [main] org.apache.nifi.bootstrap.Command Launched Apache NiFi with Process ID 48`
`2021/11/20 16:43:45 INFO [main] org.apache.nifi.toolkit.tls.standalone.TlsToolkitStandaloneCommandLine: Using /opt/nifi/nifi-current/conf/nifi.properties as template.`
`2021/11/20 16:43:46 INFO [main] org.apache.nifi.toolkit.tls.standalone.TlsToolkitStandalone: Running standalone certificate generation with output directory /opt/nifi/nifi-current/conf`
`2021/11/20 16:43:47 INFO [main] org.apache.nifi.toolkit.tls.standalone.TlsToolkitStandalone: Generated new CA certificate /opt/nifi/nifi-current/conf/nifi-cert.pem and key /opt/nifi/nifi-current/conf/nifi-key.key`
`2021/11/20 16:43:47 INFO [main] org.apache.nifi.toolkit.tls.standalone.TlsToolkitStandalone: Writing new ssl configuration to /opt/nifi/nifi-current/conf/nifi-nifi-0.nifi-nifi-headless.mvp1.svc.cluster.local`
`2021/11/20 16:43:47 INFO [main] org.apache.nifi.toolkit.tls.standalone.TlsToolkitStandalone: Successfully generated TLS configuration for nifi-nifi-0.nifi-nifi-headless.mvp1.svc.cluster.local 1 in /opt/nifi/nifi-current/conf/nifi-nifi-0.nifi-nifi-headless.mvp1.svc.cluster.local`
`2021/11/20 16:43:47 INFO [main] org.apache.nifi.toolkit.tls.standalone.TlsToolkitStandalone: Generating new client certificate /opt/nifi/nifi-current/conf/CN=admin_DC=example_DC=be.p12`
`2021/11/20 16:43:47 INFO [main] org.apache.nifi.toolkit.tls.standalone.TlsToolkitStandalone: Successfully generated client certificate /opt/nifi/nifi-current/conf/CN=admin_DC=example_DC=be.p12`
`2021/11/20 16:43:47 INFO [main] org.apache.nifi.toolkit.tls.standalone.TlsToolkitStandalone: tls-toolkit standalone completed successfully`
`Java home: /usr/local/openjdk-8`
`NiFi home: /opt/nifi/nifi-current`
`Bootstrap Config File: /opt/nifi/nifi-current/conf/bootstrap.conf`
`2021-11-20 16:43:48,780 INFO [main] org.apache.nifi.bootstrap.Command Starting Apache NiFi...`
2021-11-20 16:43:48,780 INFO [main] org.apache.nifi.bootstrap.Command Working Directory: /opt/nifi/nifi-current`
`2021-11-20 16:43:48,780 INFO [main] org.apache.nifi.bootstrap.Command Command: /usr/local/openjdk-8/bin/java -classpath /opt/nifi/nifi-current/./conf:/opt/nifi/nifi-current/./lib/jul-to-slf4j-1.7.30.jar:/opt/nifi/nifi-current/./lib/slf4j-api-1.7.30.jar:/opt/nifi/nifi-current/./lib/nifi-stateless-api-1.14.0.jar:/opt/nifi/nifi-current/./lib/jcl-over-slf4j-1.7.30.jar:/opt/nifi/nifi-current/./lib/nifi-server-api-1.14.0.jar:/opt/nifi/nifi-current/./lib/jetty-schemas-3.1.jar:/opt/nifi/nifi-current/./lib/log4j-over-slf4j-1.7.30.jar:/opt/nifi/nifi-current/./lib/logback-core-1.2.3.jar:/opt/nifi/nifi-current/./lib/logback-classic-1.2.3.jar:/opt/nifi/nifi-current/./lib/nifi-runtime-1.14.0.jar:/opt/nifi/nifi-current/./lib/nifi-framework-api-1.14.0.jar:/opt/nifi/nifi-current/./lib/nifi-nar-utils-1.14.0.jar:/opt/nifi/nifi-current/./lib/nifi-property-utils-1.14.0.jar:/opt/nifi/nifi-current/./lib/javax.servlet-api-3.1.0.jar:/opt/nifi/nifi-current/./lib/nifi-api-1.14.0.jar:/opt/nifi/nifi-current/./lib/nifi-properties-1.14.0.jar:/opt/nifi/nifi-current/./lib/nifi-stateless-bootstrap-1.14.0.jar -Dorg.apache.jasper.compiler.disablejsr199=true -Xmx2g -Xms2g -Djava.security.egd=file:/dev/urandom -Dsun.net.http.allowRestrictedHeaders=true -Djava.net.preferIPv4Stack=true -Djava.awt.headless=true -Djava.protocol.handler.pkgs=sun.net.www.protocol -Dnifi.properties.file.path=/opt/nifi/nifi-current/./conf/nifi.properties -Dnifi.bootstrap.listen.port=33724 -Dapp=NiFi -Dorg.apache.nifi.bootstrap.config.log.dir=/opt/nifi/nifi-current/logs org.apache.nifi.NiFi `
`2021-11-20 16:43:48,832 INFO [main] org.apache.nifi.bootstrap.Command Launched Apache NiFi with Process ID 100`

But after 5 minutes the pods restart and its status is `CrashLoopBackOff`.
There is nothing in the events except this one

`Back-off restarting failed container`

And also in the pods there are no logs error or warning. Can you please help me with this problem?

**Comment by banzo** [comment]
please provide the required information [asked in the issue template](.github/ISSUE_TEMPLATE/bug_report.md)

**Comment by pietrogerace1994** [comment]
I was able to solve the first problem. It was caused by a missing properties `nifi.sensitive.props.key`.
Still the server container is not able to start. This is my stacktrace

`2021-11-22 11:19:38,271 INFO [main] org.eclipse.jetty.server.Server Started @47867ms
2021-11-22 11:19:38,273 WARN [main] org.apache.nifi.web.server.JettyServer Failed to start web server... shutting down.
org.apache.nifi.web.NiFiCoreException: Unable to start Flow Controller.
        at org.apache.nifi.web.contextlistener.ApplicationStartupContextListener.contextInitialized(ApplicationStartupContextListener.java:92)
        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:1068)
        at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:572)
        at org.eclipse.jetty.server.handler.ContextHandler.contextInitialized(ContextHandler.java:997)
        at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:746)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:379)
        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1449)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1414)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:911)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:288)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.doStart(GzipHandler.java:426)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
        at org.eclipse.jetty.server.Server.start(Server.java:423)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
        at org.eclipse.jetty.server.Server.doStart(Server.java:387)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at org.apache.nifi.web.server.JettyServer.start(JettyServer.java:1129)
        at org.apache.nifi.NiFi.<init>(NiFi.java:159)
        at org.apache.nifi.NiFi.<init>(NiFi.java:71)
        at org.apache.nifi.NiFi.main(NiFi.java:303)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'loginIdentityProvider': FactoryBean threw exception on object creation; nested exception is java.io.UncheckedIOException: Writing Login Identity Providers Failed
        at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:176)
        at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:101)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1884)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getObjectForBeanInstance(AbstractAutowireCapableBeanFactory.java:1266)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:267)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1154)
        at org.apache.nifi.web.contextlistener.ApplicationStartupContextListener.contextInitialized(ApplicationStartupContextListener.java:88)
        ... 38 common frames omitted
Caused by: java.io.UncheckedIOException: Writing Login Identity Providers Failed
        at org.apache.nifi.authentication.single.user.writer.StandardLoginCredentialsWriter.writeLoginCredentials(StandardLoginCredentialsWriter.java:79)
        at org.apache.nifi.authentication.single.user.SingleUserLoginIdentityProvider.onConfigured(SingleUserLoginIdentityProvider.java:121)
        at org.apache.nifi.web.security.spring.LoginIdentityProviderFactoryBean$1.onConfigured(LoginIdentityProviderFactoryBean.java:313)
        at org.apache.nifi.web.security.spring.LoginIdentityProviderFactoryBean.getObject(LoginIdentityProviderFactoryBean.java:119)
        at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:169)
        ... 45 common frames omitted
Caused by: java.nio.file.FileSystemException: ./conf/login-identity-providers.xml: Device or resource busy
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:447)
        at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:262)
        at java.nio.file.Files.move(Files.java:1395)
        at org.apache.nifi.authentication.single.user.writer.StandardLoginCredentialsWriter.writeLoginCredentials(StandardLoginCredentialsWriter.java:77)
        ... 49 common frames omitted
2021-11-22 11:19:38,275 INFO [Thread-1] org.apache.nifi.NiFi Initiating shutdown of Jetty web server...
2021-11-22 11:19:38,283 INFO [Thread-1] o.eclipse.jetty.server.AbstractConnector Stopped ServerConnector@6486fe7b{HTTP/1.1, (http/1.1)}{172.30.3.187:8080}
2021-11-22 11:19:38,283 INFO [Thread-1] o.eclipse.jetty.server.AbstractConnector Stopped ServerConnector@4652c74d{HTTP/1.1, (http/1.1)}{127.0.0.1:8080}
2021-11-22 11:19:38,283 INFO [Thread-1] org.eclipse.jetty.server.session node0 Stopped scavenging
2021-11-22 11:19:45,369 INFO [main] org.apache.nifi.NiFi Launching NiFi...
2021-11-22 11:19:45,839 INFO [main] o.a.n.p.AbstractBootstrapPropertiesLoader Determined default application properties path to be '/opt/nifi/nifi-current/./conf/nifi.properties'
2021-11-22 11:19:45,842 INFO [main] o.a.nifi.properties.NiFiPropertiesLoader Loaded 138 properties from /opt/nifi/nifi-current/./conf/nifi.properties
2021-11-22 11:19:45,851 INFO [main] org.apache.nifi.NiFi Loaded 138 properties
2021-11-22 11:19:45,860 INFO [main] org.apache.nifi.BootstrapListener Started Bootstrap Listener, Listening for incoming requests on port 38056
2021-11-22 11:19:45,895 INFO [main] org.apache.nifi.BootstrapListener Successfully initiated communication with Bootstrap
2021-11-22 11:19:45,924 INFO [main] org.apache.nifi.nar.NarUnpacker Expanding 104 NAR files with all processors...`
