### ISSUE TITLE
Cluster not detecting zookeeper

### ISSUE THREAD

**Issue by yianni** [cetic/helm-nifi#2]
Run the helm script. 
Create a ListSFTP processor
Run the processor

This error occurs:
```
019-07-02 19:55:21,804 ERROR [Timer-Driven Process Thread-7] o.a.nifi.processors.standard.ListSFTP ListSFTP[id=b440bf38-016b-1000-0000-00004ce8fa92] Failed to properly initialize Processor. If still scheduled to run, NiFi will attempt to initialize and run the Processor again after the 'Administrative Yield Duration' has elapsed. Failure is due to java.io.IOException: Failed to obtain value from ZooKeeper for component with ID b440bf38-016b-1000-0000-00004ce8fa92 with exception code CONNECTIONLOSS: java.io.IOException: Failed to obtain value from ZooKeeper for component with ID b440bf38-016b-1000-0000-00004ce8fa92 with exception code CONNECTIONLOSS
java.io.IOException: Failed to obtain value from ZooKeeper for component with ID b440bf38-016b-1000-0000-00004ce8fa92 with exception code CONNECTIONLOSS
        at org.apache.nifi.controller.state.providers.zookeeper.ZooKeeperStateProvider.getState(ZooKeeperStateProvider.java:420)
        at org.apache.nifi.controller.state.manager.StandardStateManagerProvider$1.getState(StandardStateManagerProvider.java:288)
        at org.apache.nifi.controller.state.StandardStateManager.getState(StandardStateManager.java:63)
        at org.apache.nifi.processor.util.list.AbstractListProcessor.updateState(AbstractListProcessor.java:298)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.nifi.util.ReflectionUtils.invokeMethodsWithAnnotations(ReflectionUtils.java:142)
        at org.apache.nifi.util.ReflectionUtils.invokeMethodsWithAnnotations(ReflectionUtils.java:130)
        at org.apache.nifi.util.ReflectionUtils.invokeMethodsWithAnnotations(ReflectionUtils.java:75)
        at org.apache.nifi.util.ReflectionUtils.invokeMethodsWithAnnotation(ReflectionUtils.java:52)
        at org.apache.nifi.controller.StandardProcessorNode.lambda$initiateStart$4(StandardProcessorNode.java:1515)
        at org.apache.nifi.engine.FlowEngine$3.call(FlowEngine.java:123)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /nifi/components/b440bf38-016b-1000-0000-00004ce8fa92
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
        at org.apache.zookeeper.ZooKeeper.getData(ZooKeeper.java:1155)
        at org.apache.zookeeper.ZooKeeper.getData(ZooKeeper.java:1184)
        at org.apache.nifi.controller.state.providers.zookeeper.ZooKeeperStateProvider.getState(ZooKeeperStateProvider.java:403)
        ... 19 common frames omitted
```

**Comment by alexnuttinck** [comment]
Hello @yianni, Thanks for the report. I know there are still some works to do on this Chart. I will look at this in the next days.

**Comment by alexnuttinck** [comment]
I have made some modifications on the Helm chart. Could you retry with the last version? 

If this error still occurs, did you change something in the `values.yaml` file?

**Comment by yianni** [comment]
@alexnuttinck The modifications fixed the issue. Great job!

**Comment by alexnuttinck** [comment]
Thanks @yianni! I close this issue.
