### ISSUE TITLE
[cetic/nifi] Pending indefinitely

### ISSUE THREAD

**Issue by bloudman** [cetic/helm-nifi#34]
Hi, 
I'm in trouble with the new version of this helm file (1.10.0)
All containers "PodInitializing" indefinitely.

How can I fix this issue.

Here are the events logs on GCP:

```


Message | Reason | First Seen | Last Seen | Count
-- | -- | -- | -- | --
Started container | Started | Dec 9, 2019, 2:54:42 PM | Dec 9, 2019, 2:54:42 PM | 1
pulling image "busybox" | Pulling | Dec 9, 2019, 2:54:41 PM | Dec 9, 2019, 2:54:41 PM | 1
Successfully pulled image "busybox" | Pulled | Dec 9, 2019, 2:54:41 PM | Dec 9, 2019, 2:54:41 PM | 1
Created container | Created | Dec 9, 2019, 2:54:41 PM | Dec 9, 2019, 2:54:41 PM | 1
Successfully assigned test/apache-nifi-test-0 to gke-foundry-02-tools-47303935-njrt | Scheduled | Dec 9, 2019, 2:54:40 PM | Dec 9, 2019, 2:54:40 PM | 1
Successfully pulled image "busybox" | Pulled | Dec 9, 2019, 2:48:22 PM | Dec 9, 2019, 2:48:22 PM | 1
Created container | Created | Dec 9, 2019, 2:48:22 PM | Dec 9, 2019, 2:48:22 PM | 1
Started container | Started | Dec 9, 2019, 2:48:22 PM | Dec 9, 2019, 2:48:22 PM | 1
pulling image "busybox" | Pulling | Dec 9, 2019, 2:48:21 PM | Dec 9, 2019, 2:48:21 PM | 1
Successfully assigned test/apache-nifi-test-0 to gke-foundry-02-tools-47303935-njrt | Scheduled | Dec 9, 2019, 2:48:20 PM | Dec 9, 2019, 2:48:20 PM | 1


```

**Comment by alexnuttinck** [comment]
Hi @bloudman ,
Can you **Describe the bug** a bit more?

*  Which version of Helm and Kubernetes do you use?
*  How to reproduce it? (as minimally and precisely as possible) Do you change the default values file?
* Anything else we need to know?
* What should I see in your logs?

**Comment by bloudman** [comment]
Hi @alexnuttinck,

I'm using helm v2.14.1, Kubernetes 1.13.11-gke.14.

My values.yml file:
```
---
# Number of nifi nodes
replicaCount: 1

## Set default image, imageTag, and imagePullPolicy. 
## ref: https://hub.docker.com/r/apache/nifi/
##
image:
  repository: apache/nifi
  tag: "1.10.0"
  pullPolicy: IfNotPresent

  ## Optionally specify an imagePullSecret.
  ## Secret must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  # pullSecret: myRegistrKeySecretName

securityContext:
  runAsUser: 1000
  fsGroup: 1000

sts:
  # Parallel podManagementPolicy for faster bootstrap and teardown. Default is OrderedReady.
  podManagementPolicy: Parallel
  AntiAffinity: soft
  hostPort: null

## Useful if using any custom secrets
## Pass in some secrets to use (if required)
# secrets:
# - name: myNifiSecret
#   keys:
#     - key1
#     - key2
#   mountPath: /opt/nifi/secret

properties:
  # use externalSecure for when inbound SSL is provided by nginx-ingress or other external mechanism
  externalSecure: false
  isNode: true
  httpPort: 8080
  httpsPort: null
  clusterPort: 6007
  clusterSecure: false
  needClientAuth: false
  provenanceStorage: "8 GB"
  siteToSite:
    secure: false
    port: 10000
  authorizer: managed-authorizer
  # use properties.safetyValve to pass explicit 'key: value' pairs that overwrite other configuration
  # safetyValve:
    #nifi.variable.registry.properties: "${NIFI_HOME}/example1.properties, ${NIFI_HOME}/example2.properties"

## Include additional libraries in the Nifi containers by using the postStart handler
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/attach-handler-lifecycle-event/
# postStart: /opt/nifi/psql; wget -P /opt/nifi/psql https://jdbc.postgresql.org/download/postgresql-42.2.6.jar

# Nifi User Authentication
auth:
  ldap:
    enabled: false
    host: ldap://<hostname>:<port>
    searchBase: CN=Users,DC=example,DC=com
    searchFilter: CN=john

## Expose the nifi service to be accessed from outside the cluster (LoadBalancer service).
## or access it from within the cluster (ClusterIP service). Set the service type and the port to serve it.
## ref: http://kubernetes.io/docs/user-guide/services/
##

# headless service
headless:
  type: ClusterIP
  annotations: 
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"

# ui service
service:
  type: ClusterIP
  httpPort: 80
  httpsPort: 443
  annotations: {}
  # loadBalancerIP:
  ## Load Balancer sources
  ## https://kubernetes.io/docs/tasks/access-application-cluster/configure-cloud-provider-firewall/#restrict-access-for-loadbalancer-service
  ##
  # loadBalancerSourceRanges:
  # - 10.10.10.0/24

## Configure Ingress based on the documentation here: https://kubernetes.io/docs/concepts/services-networking/ingress/
##
ingress:
  enabled: false
  annotations: {}
  tls: []
  hosts: []
  path: /

# Amount of memory to give the NiFi java heap
jvmMemory: 2g

# Separate image for tailing each log separately
sidecar:
  image: ez123/alpine-tini

## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  enabled: false

  # When creating persistent storage, the NiFi helm chart can either reference an already-defined
  # storage class by name, such as "standard" or can define a custom storage class by specifying
  # customStorageClass: true and providing the "storageClass", "storageProvisioner" and "storageType".
  # For example, to use SSD storage on Google Compute Engine see values-gcp.yaml
  #
  # To use a storage class that already exists on the Kubernetes cluster, we can simply reference it by name.
  # For example:
  # storageClass: standard
  #
  # The default storage class is used if this variable is not set.

  accessModes:  [ReadWriteOnce]
  ## Storage Capacities for persistent volumes
  # Storage capacity for the 'data' directory, which is used to hold things such as the flow.xml.gz, configuration, state, etc.
  dataStorage: 
    size: 1Gi
  # Storage capacity for the FlowFile repository
  flowfileRepoStorage: 
    size: 10Gi
  # Storage capacity for the Content repository
  contentRepoStorage: 
    size: 10Gi
  # Storage capacity for the Provenance repository. When changing this, one should also change the properties.provenanceStorage value above, also.
  provenanceRepoStorage: 
    size: 10Gi
  # Storage capacity for nifi logs
  logStorage: 
    size: 5Gi

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

logresources:
  requests:
    cpu: 10m
    memory: 10Mi
  limits:
    cpu: 50m
    memory: 50Mi

nodeSelector: {}

tolerations: []

# ------------------------------------------------------------------------------
# Zookeeper:
# ------------------------------------------------------------------------------
zookeeper:
  ## If true, install the Zookeeper chart
  ## ref: https://github.com/kubernetes/charts/tree/master/incubator/zookeeper
  enabled: true

  ## If the Zookeeper Chart is disabled a URL and port are required to connect
  url: ""
  port: 2181

```
To reproduce it : `helm install --name apache-nifi-test --namespace test -f values.yaml cetic/nifi`

The problem seems to come from Zookeeper that gives me a crashLoopBackOff:
```
2019-12-09T14:42:15.822259302Z 2019-12-09 14:42:15,821 [myid:1] - WARN  [main:ContextHandler@1599] - Empty contextPath
 I 
2019-12-09T14:42:15.853258007Z 2019-12-09 14:42:15,852 [myid:1] - INFO  [main:X509Util@79] - Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation
 I 
2019-12-09T14:42:15.864496819Z 2019-12-09 14:42:15,862 [myid:1] - INFO  [main:QuorumPeer@1488] - Local sessions disabled
 I 
2019-12-09T14:42:15.865072458Z 2019-12-09 14:42:15,864 [myid:1] - INFO  [main:QuorumPeer@1499] - Local session upgrading disabled
 I 
2019-12-09T14:42:15.865420937Z 2019-12-09 14:42:15,865 [myid:1] - INFO  [main:QuorumPeer@1466] - tickTime set to 2000
 I 
2019-12-09T14:42:15.865745920Z 2019-12-09 14:42:15,865 [myid:1] - INFO  [main:QuorumPeer@1510] - minSessionTimeout set to 4000
 I 
2019-12-09T14:42:15.866034760Z 2019-12-09 14:42:15,865 [myid:1] - INFO  [main:QuorumPeer@1521] - maxSessionTimeout set to 40000
 I 
2019-12-09T14:42:15.866279120Z 2019-12-09 14:42:15,866 [myid:1] - INFO  [main:QuorumPeer@1536] - initLimit set to 10
 I 
2019-12-09T14:42:15.886940633Z 2019-12-09 14:42:15,886 [myid:1] - INFO  [main:ZKDatabase@117] - zookeeper.snapshotSizeFactor = 0.33
 I 
2019-12-09T14:42:15.889852982Z 2019-12-09 14:42:15,889 [myid:1] - INFO  [main:QuorumPeer@1781] - Using insecure (non-TLS) quorum communication
 I 
2019-12-09T14:42:15.890298497Z 2019-12-09 14:42:15,890 [myid:1] - INFO  [main:QuorumPeer@1787] - Port unification disabled
 I 
2019-12-09T14:42:15.890650635Z 2019-12-09 14:42:15,890 [myid:1] - INFO  [main:QuorumPeer@2154] - QuorumPeer communication is not secured! (SASL auth disabled)
 I 
2019-12-09T14:42:15.890954766Z 2019-12-09 14:42:15,890 [myid:1] - INFO  [main:QuorumPeer@2183] - quorum.cnxn.threads.size set to 20
 I 
2019-12-09T14:42:15.940967592Z 2019-12-09 14:42:15,909 [myid:1] - ERROR [main:QuorumPeer@955] - Unable to load database on disk
 I 
2019-12-09T14:42:15.941008282Z java.io.IOException: No snapshot found, but there are log entries. Something is broken!
	at org.apache.zookeeper.server.persistence.FileTxnSnapLog.restore(FileTxnSnapLog.java:211)
	at org.apache.zookeeper.server.ZKDatabase.loadDataBase(ZKDatabase.java:240)
	at org.apache.zookeeper.server.quorum.QuorumPeer.loadDataBase(QuorumPeer.java:919)
	at org.apache.zookeeper.server.quorum.QuorumPeer.start(QuorumPeer.java:905)
	at org.apache.zookeeper.server.quorum.QuorumPeerMain.runFromConfig(QuorumPeerMain.java:205)
	at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:123)
	at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:82)
 I 
2019-12-09T14:42:15.941927722Z 2019-12-09 14:42:15,940 [myid:1] - ERROR [main:QuorumPeerMain@101] - Unexpected exception, exiting abnormally
 I 
````

**Comment by alexnuttinck** [comment]
@bloudman Thank you for the description.

Maybe you kept the storage of an old zookeeper. 
Can you try to delete your old PVC of zookeeper and retry?

**Comment by bloudman** [comment]
@alexnuttinck  Thanks it's working fine now!
I have another problem now I launched 2 apache nifi replicas, the first one is ok and is working fine but the second one is unhealthy and restart in an infinite loop (now 164 restarts...).

```
Readiness probe failed: Node not found with CONNECTED state. Full cluster state: % Total % Received % Xferd Average Speed Time Time Time Current Dload Upload Total Spent Left Speed 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0* Trying 10.48.14.91... * TCP_NODELAY set * connect to 10.48.14.91 port 8080 failed: Connection refused * Failed to connect to apache-nifi-test-1.apache-nifi-test-headless.test.svc.cluster.local port 8080: Connection refused * Closing connection 0 curl: (7) Failed to connect to apache-nifi-test-1.apache-nifi-test-headless.test.svc.cluster.local port 8080: Connection refused
``` 
I had the same trouble last week with the older version I'm totally unable to solve it.
Do you have any idea ?
